setting:
  location:
    city: 花蓮縣
    town: 花蓮市
    lat: 23.9820651
    lon: 121.6067705
  warning:
    realtime-station: 0級
    estimate-int: 0級
  bg-filter: 20
  bg-percentage: 100
  map-display-effect: 1
  station:
    name: '6110036'
    net: SE-Net
    loc: 花蓮縣花蓮市
    code: 970
    lat: 23.9732551
    lon: 121.6068999
  user-checkbox:
    early-warning-TREM: 1
    early-warning-CWA: 0
    early-warning-JMA: 1
    early-warning-NIED: 1
    early-warning-KMA: 1
    early-warning-SCDZJ: 1
    show-window-eew: 1
    show-window-report: 1
    show-window-detect: 1
    show-window-realtime-int: 1
    other-auto-start: 1
    other-voice: 1
    graphics-block-auto-zoom: 1
    graphics-show-fault: 1
    sound-effects-dong: 1
    sound-effects-EEW: 1
    sound-effects-EEW2: 1
    sound-effects-PAlert: 1
    sound-effects-PGA1: 1
    sound-effects-PGA2: 1
    sound-effects-Report: 1
    sound-effects-Shindo0: 1
    sound-effects-Shindo1: 1
    sound-effects-Shindo2: 1
    sound-effects-Update: 1
  login: 44428bb83e548a6
  tos: 1
