setting:
  location:
    city: 苗栗縣
    town: 竹南鎮
    lat: 24.6838448
    lon: 120.8733503
  warning:
    realtime-station: 5強
    estimate-int: 2級
  bg-filter: 20
  bg-percentage: 100
  map-display-effect: '4'
  station:
    net: SE-Net
    code: '600'
    name: '4568880'
    loc: 嘉義市東區
    lat: '23.4539778'
    lon: '120.4559805'
  user-checkbox:
    early-warning-CWA: 1
    early-warning-JMA: 1
    early-warning-NIED: 1
    early-warning-KMA: 1
    early-warning-SCDZJ: 1
    show-window-eew: 1
    show-window-report: 1
    show-window-detect: 1
    show-window-realtime-int: 1
    early-warning-TREM: 1
    other-auto-start: 1
    other-voice: 1
    graphics-block-auto-zoom: 1
    graphics-show-fault: 1
    sound-effects-dong: 1
    sound-effects-EEW: 1
    sound-effects-EEW2: 1
    sound-effects-PAlert: 1
    sound-effects-PGA1: 1
    sound-effects-PGA2: 1
    sound-effects-Report: 1
    sound-effects-Shindo0: 1
    sound-effects-Shindo1: 1
    sound-effects-Shindo2: 1
    sound-effects-Update: 1
  login: ''
  tos: 1
