setting:
  location:
    city: 屏東縣
    town: 屏東市
    lat: 22.662498
    lon: 120.4914295
  warning:
    realtime-station: 0級
    estimate-int: 0級
  bg-filter: 20
  bg-percentage: 100
  map-display-effect: 1
  station:
    name: '15007248'
    net: SE-Net
    loc: 屏東縣九如鄉
    code: 904
    lat: 22.748288
    lon: 120.4815409
  user-checkbox:
    early-warning-CWA: 1
    early-warning-JMA: 1
    early-warning-KMA: 1
    early-warning-NIED: 1
    early-warning-SCDZJ: 1
    graphics-block-auto-zoom: 1
    graphics-show-plates: 1
    other-auto-start: 1
    other-voice: 1
    show-window-detect: 1
    show-window-eew: 1
    show-window-realtime-int: 1
    show-window-report: 1
    sound-effects-EEW: 1
    sound-effects-EEW2: 1
    sound-effects-PAlert: 1
    sound-effects-PGA1: 1
    sound-effects-PGA2: 1
    sound-effects-Report: 1
    sound-effects-Shindo0: 1
    sound-effects-Shindo1: 1
    sound-effects-Shindo2: 1
    sound-effects-Update: 1
    sound-effects-dong: 1
  login: ''
  tos: 1
